stages:
- stage: stage1
  jobs:
  - job: MyJob
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - powershell: Write-Host "$(pipeline.resourcesdirectory)"

      - task: PublishBuildArtifacts@1
        displayName: Publish TestFolder
        inputs:
          pathToPublish: testFolder
          artifactName: Artifact1

      - task: PublishBuildArtifacts@1
        displayName: Publish yml
        inputs: 
          pathToPublish: azure-pipelines.yml
          artifactName: Artifact2

  - job: MyJob2
    dependsOn: MyJob
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - download: current
        artifact: Artifact1
        patterns: ['**/*.cmd', '**/*.ps1']
        #patterns: '**/*.cmd;**/*.ps1'

      - download: current
        artifact: Artifact2
        root: "$(system.defaultworkingdirectory)/hello/test"
        
      #- downloadArtifact:
      #  name: Artifact2
      - task: PublishBuildArtifacts@1
        displayName: Publish NewTestFolder
        inputs:
          pathToPublish: NewTestFolder
          artifactName: NewTestFolder
          
      #- task: DownloadBuildArtifacts@0
      #  displayName: download artifact1
      #  inputs:
      #    artifactName: Artifact2
          
 # - job: MyJob3
 #   timeoutInMinutes: 2
 #   cancelTimeoutInMinutes: 2
 #   dependsOn: MyJob
 #   
 #   pool:
 #     name: 'Default'
 #
 #   steps:
 #     - script: echo Hello MyJob3

- stage: stage2
  dependsOn: stage1
  jobs:
    - job: MyJobFromStage2

      pool:
        name: 'Default'
      
      steps:
        - script: echo I am stage2 MyJob
        - download: current
          patterns: '**/*.txt'
