# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

pool:
  name: 'Default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: Publish TestFolder
  inputs:
    pathToPublish: testFolder
    artifactName: Artifact1

- download: current
  artifact: Artifact1
  enabled: false
- download: current
  artifact: Artifact1
  name: MyArtifact1
  displayName: download-myartifact1
#test