stages:
- stage: stage1
  jobs:
  - job: Job1
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - task: PublishBuildArtifacts@1
        displayName: Publish TestFolder
        inputs:
          pathToPublish: testFolder
          artifactName: Artifact1

      - task: PublishBuildArtifacts@1
        displayName: Publish yml
        inputs: 
          pathToPublish: azure-pipelines.yml
          artifactName: Artifact2
  
  
  - job: Download_all_by_default
    displayName: Download all artifacts by default
    dependsOn: Job1
    pool:
      name: 'Default'
    steps:
      - script: echo Will download all artifacts uploaded in Job1
  
  
  - job: Download_only_specific_artifact
    displayName: Download only specific artifact
    dependsOn: Job1
    pool:
      name: 'Default'

    steps:
      - download: current
        artifact: Artifact1
        
  - job: Download_none
    displayName: Don't download any artifact
    dependsOn: Job1
    pool:
      name: 'Default'
    steps:
      - download: none

#----- download optimization begin --------------------#
  - job: Download_Optimization_for_selfinjected_task
    displayName: Don't download automatically if no dependency
    pool:
      name: 'Default'
    steps:
      - download: none

  - job: No_Download_Optimization_for_user_task
    displayName: Download and try to fail user task when there is no dependency
    pool:
      name: 'Default'
    steps:
       - download: current
         artifact: Artifact1000
#----- download optimization end --------------------#


        #patterns: ['**/*.cmd', '**/*.ps1']
        #patterns: '**/*.cmd;**/*.ps1'

      #- download: current
      #  artifact: Artifact2
      #  root: "$(system.defaultworkingdirectory)/hello/test"
        
      #- downloadArtifact:
      #  name: Artifact2
      #- task: PublishBuildArtifacts@1
      #  displayName: Publish NewTestFolder
      #  inputs:
      #    pathToPublish: NewTestFolder
      #    artifactName: NewTestFolder
          
      #- task: DownloadBuildArtifacts@0
      #  displayName: download artifact1
      #  inputs:
      #    artifactName: Artifact2
          
 # - job: MyJob3
 #   timeoutInMinutes: 2
 #   cancelTimeoutInMinutes: 2
 #   dependsOn: MyJob
 #   
 #   pool:
 #     name: 'Default'
 #
 #   steps:
 #     - script: echo Hello MyJob3

- stage: stage2
  dependsOn: stage1
  jobs:
    - job: MyJobFromStage2

      pool:
        name: 'Default'
      
      steps:
        - script: echo I am stage2 MyJob
        - download: current
          patterns: '**/*.txt'
