stages:
- stage: stage1
  jobs:
  - job: MyJob
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - script: echo Hello world

      - task: PublishBuildArtifacts@1
        displayName: Publish ReadMe
        inputs:
          pathToPublish: testFolder
          artifactName: Artifact1

      - task: PublishBuildArtifacts@1
        displayName: Publish yml
        inputs:
          pathToPublish: azure-pipelines.yml
          artifactName: Artifact2

  - job: MyJob2
    dependsOn: MyJob
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - downloadArtifact:
        name: Artifact1
        pattern: '**/*.txt'
        
      - downloadArtifact:
        name: Artifact2

      - script: echo Hello world2

      - task: PublishBuildArtifacts@1
        displayName: Publish NewTestFolder
        inputs:
          pathToPublish: NewTestFolder
          artifactName: NewTestFolder
          
      #- task: DownloadBuildArtifacts@0
      #  displayName: download artifact1
      #  inputs:
      #    artifactName: Artifact2
          
  - job: MyJob3
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2
    dependsOn: MyJob
    
    pool:
      name: 'Default'

    steps:
      - script: echo Hello MyJob3

- stage: stage2
  dependsOn: stage1
  jobs:
    - job: MyJobFromStage2

      pool:
        name: 'Default'
      
      steps:
        - script: echo I am stage2 MyJob
        - downloadArtifact:
