resources:
  pipelines:
  - pipeline: MyPipeline
    project: MyFirstProject
    source: MyFirstProject
    version: 20190314.4
  - pipeline: MyPipeline2
    project: MyFirstProject
    source: MyFirstProject
   #version: 20190109.6
    
jobs:
  - job: download_external_artifact
    displayName: download all artifact
    pool:
      name: 'Default'
    steps:
      - script: echo download all external artifact
      - task: PublishBuildArtifacts@1
        displayName: Publish TestFolder-internal
        inputs:
          pathToPublish: testFolder
          artifactName: Artifact1-internal
      - download: MyPipeline2
        artifact: ExtensionZip    
      - download: MyPipeline
        artifact: ExtensionZip    
  - job: download_specific_artifact
    dependsOn: download_external_artifact
    displayName: download specific artifact
    pool:
      name: 'Default'
    steps:
      - download: current
        artifact: Artifact1-internal
      - download: MyPipeline
        artifact: Artifact1

  - job: download_all_artifact
    dependsOn: download_external_artifact
    displayName: download all artifact
    pool: 'Default'