resources:
  builds:
  - build: MyJenkins
    type: Jenkins
    connection: rmcdp
    source: FreeStyleProject
    version: 45

jobs:
  - job: job1
    pool: 'Default'
    steps:
      - script: echo download all artifact
      #- downloadBuild: MyJenkins
      #  name: MyJob


