resources:
  builds:
  - build: MyJenkins
    type: Jenkins
    connection: kalyan-dev
    source: github
    version: 30
    
jobs:
  - job: job1
    pool: 'Default'
    steps:
      - script: echo download all artifact
      - downloadBuild: MyJenkins
        path: $(Pipeline.workspace)/foo
      #   displayName: Download Folder project
      #   patterns: '*.txt'


