resources:
  builds:
  - build: MyJenkins
    type: Jenkins
    connection: rmcdp
    source: FreeStyleProject
    version: 45
  - build: MyJenkins2
    type: Jenkins
    connection: rmcdp
    source: FreeStyleProject

jobs:
  - job: job1
    pool: 'Default'
    steps:
      - script: echo download all artifact
      - downloadBuild: MyJenkins
        displayName: Download FreeStyle project


