resources:
  builds:
  - build: MyJenkins
    type: Jenkins
    connection: kalyan-dev
    source: github
    version: 30
    
jobs:
  - job: job1
    pool: 'Default'
    steps:
      - script: echo download all artifact
      - downloadBuild: MyJenkins
        path: $(Pipeline.workspace)/foo
      - downloadBuild: MyJenkins
      #   displayName: Download Folder project
      #   patterns: '*.txt'

  - deployment: Deploy
    displayName: Deploy job
    pool: default
    environment: Environment01
    strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hello, world! This is deploy job
                displayName: 'Run a one-line script'
              - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
                displayName: Explore workspace
