resources:
  builds:
  - build: MyJenkins
    type: Jenkins
    connection: kalyan-dev
    source: github

jobs:
  - job: job1
    pool: 'Default'
    steps:
      - script: echo download all artifact
      # - downloadBuild: MyJenkins2
      #   displayName: Download Folder project
      #   patterns: '*.txt'


