resources:
  pipelines:
  - pipeline: MyPipeline2
    project: MyFirstProject
    source: MyFirstProject

  builds:
  - build: MyJenkins
    type: Jenkins
    connection: rmcdp
    source: FreeStyleProject
    version: 47

jobs:
  - job: job1
    pool: 'Default'
    steps:
      - script: echo download all artifact
      #- downloadBuild: MyJenkins
      #  name: MyJob


