stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: default
    steps:
    # - upload: testFolder
    #   artifact: Artifact1
      - task: PublishBuildArtifacts@1
        displayName: Publish yml
        inputs: 
          pathToPublish: azure-pipelines.yml
          artifactName: Artifact2

- stage: QA
  displayName: QA stage
  jobs:
  - job: dummyJob2
    pool: default
    steps:
      - download: current
        path: foo
        continueOnError: true
      - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
        displayName: Explore workspace
      # - powershell: |
      #     Remove-Item $(Pipeline.Workspace)\foo -Recurse -Force
      #   displayName: Scorch workspace

- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy
    displayName: Deploy job
    pool: default
    environment: Environment01
    strategy:
        runOnce:
          deploy:
            steps:
              - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
                displayName: Explore workspace

              # - powershell: |
              #     Remove-Item $(Pipeline.Workspace)\Artifact1 -Recurse -Force
              #   displayName: Scorch workspace
