trigger:
- master
  
stages:
- stage: stage1
  jobs:
  - job: Job1
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'
    steps:
      - upload: Extension/vsix
        artifact: Extension

      # - task: PublishPipelineArtifact@0
      #   displayName: Upload Vsix File
      #   inputs:
      #     artifactName: Extension
      #     targetPath: Extension/vsix
          
      - task: PublishPipelineArtifact@0
        displayName: Upload Vsix Zip File
        inputs:
          artifactName: ExtensionZip
          targetPath: Extension/Zip

      - task: PublishBuildArtifacts@1
        displayName: Publish TestFolder
        inputs:
          pathToPublish: testFolder
          artifactName: Artifact1          

  # - job: Download_all_by_default
  #   displayName: Download all artifacts by default
  #   dependsOn: Job1
  #   pool: 'Default'
  #   steps:
  #     - script: echo Will download all artifacts uploaded in Job1
  
  # - job: Download_only_specific_artifact
  #   displayName: Download only specific artifact with layout provided by pipeline
  #   dependsOn: Job1
  #   pool: 'Default'
  #   steps:
  #     - download: current
  #       artifact: Extension
  
  # - job: job3
  #   displayName: Download only specific artifact with layout provided by customer
  #   dependsOn: Job1
  #   pool: 'Default'
  #   steps:
  #     - download: current
  #       artifact: ExtensionZip
  #       path: mypath

  # - job: job4
  #   displayName: apply attributes to all artifacts
  #   dependsOn: Job1
  #   pool: 'Default'
  #   steps:
  #     - download: current
  #       path: zip
  #       patterns: '*.md'

  - job: job4
    displayName: apply attributes to all artifacts multiline patterns
    dependsOn: Job1
    pool: 'Default'
    steps:
      - download: current
        path: extensionzipfolder
        patterns: |
          *.md
          *.vsix
