trigger: none 
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    #pool: default
    pool: kasubram-test
    steps:
    - script: echo Hello, world! This is CI job
      displayName: 'Run a one-line script'

    # - task: PublishPipelineArtifact@0
    #   displayName: Create Artifact
    #   inputs:
    #     artifactName: Artifact1
    #     targetPath: testFolder

    - task: PublishBuildArtifacts@1
      displayName: Publish TestFolder
      inputs:
        pathToPublish: testFolder
        artifactName: Artifact1

    - upload: Extension
      artifact: Artifact2

- stage: QA
  displayName: QA stage
  jobs:
  - job: dummyJob1
    #pool: default
    pool: kasubram-test
    steps:
      - script: echo Hello, world! This is dummy job
        displayName: 'Run a one-line script'
      - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
        displayName: Explore Workspace

  - job: dummyJob2
    #pool: default
    pool: kasubram-test
    steps:
      - download: current
        path: foo
      - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
        displayName: Explore Workspace
      - powershell: |
          Remove-Item $(Pipeline.Workspace)\foo -Recurse -Force
        displayName: Scorch workspace

#   - job: dummyJob3
#     #pool: default
#     pool: hosted
#     steps:
#       - download: current
#         patterns: '*.txt'
#       - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
#         displayName: Explore Workspace
#       - powershell: |
#           Remove-Item $(Pipeline.Workspace)\Artifact1 -Recurse -Force
#           Remove-Item $(Pipeline.Workspace)\Artifact2 -Recurse -Force
#         displayName: Scorch workspace


#   - job: dummyJob4
#     #pool: default
#     pool: hosted
#     steps:
#       - download: current
#         artifact: artifact1
#         path: bar
#       - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
#         displayName: Explore Workspace
#       - powershell: |
#           Remove-Item $(Pipeline.Workspace)\bar -Recurse -Force
#         displayName: Scorch workspace

#   - job: dummyJob5
#     #pool: default
#     pool: hosted
#     steps:
#       - download: current
#         artifact: artifact1
#       - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
#         displayName: Explore Workspace
#       - powershell: |
#           Remove-Item $(Pipeline.Workspace)\artifact1 -Recurse -Force
#         displayName: Scorch workspace

#   - job: dummyJob6
#     #pool: default
#     pool: hosted
#     steps:
#       - download: none
#       - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
#         displayName: Explore Workspace
      
- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy1
    displayName: Deploy job
    #pool: default
    pool: kasubram-test
    environment: Environment01
    strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hello, world! This is deploy job
                displayName: 'Run a one-line script'
              - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
                displayName: Explore workspace

              - powershell: |
                  # Remove-Item $(Pipeline.Workspace)\Artifact1 -Recurse -Force
                  Remove-Item $(Pipeline.Workspace)\Artifact2 -Recurse -Force
                displayName: Scorch workspace

              - task: PublishPipelineArtifact@0
                displayName: Create Azcopy Artifact
                inputs:
                  artifactName: AzCopy
                  targetPath: Files/azcopyFiles

  - deployment: Deploy2
    displayName: Deploy2 job
    #pool: default
    pool: kasubram-test
    environment: Environment01
    dependsOn: Deploy1
    strategy:
        runOnce:
          deploy:
            steps:
              - script: echo Hello, world! This is deploy job
                displayName: 'Run a one-line script'
              - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
                displayName: Explore workspace

              - powershell: |
                  Remove-Item $(Pipeline.Workspace)\Azcopy -Recurse -Force
                displayName: Scorch workspace

  # - deployment: Deploy3
  #   displayName: Deploy3 job
  #   #pool: default
  #   pool: kasubram-test
  #   environment: Environment01
  #   dependsOn: Deploy1
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - download: current
  #               path: foo
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore Workspace
  #             - powershell: |
  #                 Remove-Item $(Pipeline.Workspace)\foo -Recurse -Force
  #               displayName: Scorch workspace

  # - deployment: Deploy4
  #   displayName: Deploy4 job
  #   #pool: default
  #   pool: kasubram-test
  #   environment: Environment01
  #   dependsOn: Deploy1
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - download: current
  #               patterns: |
  #                 *.vsix
  #                 *.vsomanifest
  #                 *.txt
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore Workspace
  #             - powershell: |
  #                 Remove-Item $(Pipeline.Workspace)\Artifact1 -Recurse -Force
  #                 Remove-Item $(Pipeline.Workspace)\Artifact2 -Recurse -Force
  #               displayName: Scorch workspace

  # - deployment: Deploy5
  #   displayName: Deploy5 job
  #   #pool: default
  #   pool: kasubram-test
  #   environment: Environment01
  #   dependsOn: Deploy1
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - download: current
  #               artifact: artifact1
  #               path: bar
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore Workspace
  #             - powershell: |
  #                 Remove-Item $(Pipeline.Workspace)\bar -Recurse -Force
  #               displayName: Scorch workspace

  # - deployment: Deploy6
  #   displayName: Deploy6 job
  #   #pool: default
  #   pool: kasubram-test
  #   environment: Environment01
  #   dependsOn: Deploy1
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - download: current
  #               artifact: artifact1
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore Workspace
  #             - powershell: |
  #                 Remove-Item $(Pipeline.Workspace)\artifact1 -Recurse -Force
  #               displayName: Scorch workspace

  # - deployment: Deploy7
  #   displayName: Deploy7 job
  #   #pool: default
  #   pool: kasubram-test
  #   environment: Environment01
  #   dependsOn: Deploy1
  #   strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #             - script: echo Hello, world! This is deploy job
  #               displayName: 'Run a one-line script'
  #             - download: none
  #             - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory
  #               displayName: Explore Workspace

  # # - deployment: DeployOnServer
  # #   displayName: Deploy job
  # #   pool: server
  # #   environment: Environment01
  # #   strategy:
  # #       runOnce:
  # #         deploy:
  # #           steps:
  # #           - task: Delay@1
  # #             inputs:
  # #               delayForMinutes: '1' 
                
