trigger: none
pool: default

resources:
 pipelines:
   - pipeline: mypipeline
     source:  MyFirstProject
     #trigger: true

# steps:
# - checkout: none
# - download: mypipeline
extends:
  template: template.yml
  parameters:
      yesNo: false 