trigger: none
resources:
 builds:
     - build: mybuild
       type: Jenkins
       connection: rmcdpjenkins3
       source: rogoyal
 containers:
   - container: Constoso
     type: ACR
     azureSubscription: ashkir_rmpm_kasubram
     resourceGroup: ashkir
     registry: ashkirACR
     repository: ashokirlaahsimplegorepo

steps:
- checkout: none
- downloadBuild: mybuild
