trigger: none

resources:
 webhooks:
     - webhook: mywebhook
       connection: webhook1
#test2


steps:
- checkout: none
- powershell: Write-Host "${{ parameters.mywebhook.repository.owner.email }}"