trigger: none

resources:
 webhooks:
     - webhook: mywebhook
       connection: webhook1
       filters:
         - path: repository.owner.name
           value: kasubram
#test


steps:
- checkout: none
- powershell: Write-Host "${{ parameters.mywebhook.repository.owner.email }}"