resources:
  pipelines:
  - pipeline: MyPipeline
    type: build
    definition: First
    
jobs:
  - job: MyJob
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - script: echo Hello world
      - downloadArtifacts: MyPipeline
