resources:
  pipelines:
  - pipeline: MyPipeline
    project: p1
    source: source-pipeline
    trigger:
      branches:
        include:
        - master
        exclude:
        - release

stages:
- stage: stage1
  jobs:
  - job: Job1
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - powershell: Write-Host "HelloWorld"

#test1
#test2
#test3
#test4
#test5