resources:
  pipelines:
  - pipeline: MyPipeline
    project: p1
    source: source-pipeline
    trigger:
      branches:
        include:
        - master
        exclude:
        - release
      stages:
      - Build
  - pipeline: MyPipeline2
    project: p1
    source: source-pipeline
    trigger:
      branches:
        - release
      # tags:
      #   - test1
      #  - test3
      stages:
      - __default

  - pipeline: MyPipeline3
    project: p2
    source: p2
    trigger:
      branches:
        include:
        - releases/*
        exclude:
        - release

jobs:
- job: Job1
  pool: default

  steps:
    - powershell: Write-Host "HelloWorld"

#test11
