resources:
  pipelines:
  - pipeline: MyPipeline
    project: p1
    source: source-pipeline
    trigger:
      branches:
        include:
        - master
        exclude:
        - release
  - pipeline: MyPipeline2
    project: p1
    source: source-pipeline
    trigger:
      branches:
        - release
      tags:
        - test1
        - test2

jobs:
- job: Job1
  pool: default

  steps:
    - powershell: Write-Host "HelloWorld"

#test1
