trigger: none

resources:
  pipelines:
  - pipeline: MyPipeline
    #project: p1
    source: Source Build
    trigger: 
      branches:
        include:
        - master
#         - test
#         exclude:
#         - release/*
      # stages:
      # - Build
      # - Dev
  # - pipeline: MyPipeline2
  #   project: p1
  #   source: source-pipeline
  #   trigger:
  #     branches:
  #       - release
  #     # tags:
  #     #   - test1
  #     #  - test3
  #     stages:
  #     - __default

  # - pipeline: MyPipeline3
  #   project: p2
  #   source: p2
  #   trigger:
  #     branches:
  #       include:
  #       - releases/*
  #       exclude:
  #       - release

jobs:
- job: Job1
  pool: default

  steps:
    - checkout: none
    - download: MyPipeline

#test11
