stages:
- stage: stage1
  jobs:
  - job: Job1
    timeoutInMinutes: 2
    cancelTimeoutInMinutes: 2

    pool:
      name: 'Default'

    steps:
      - task: PublishBuildArtifacts@1
        displayName: Publish TestFolder
        inputs:
          pathToPublish: testFolder
          artifactName: Artifact1

      - task: PublishBuildArtifacts@1
        displayName: Publish yml
        inputs: 
          pathToPublish: azure-pipelines.yml
          artifactName: Artifact2
  
      - task: PublishBuildArtifacts@1
        displayName: Publish AzCopy Files
        inputs:
          pathToPublish: Files/azcopyFiles
          artifactName: AzCopy
          artifactType: filePath
          targetPath: \\kalyan-dev\share\agentartifactfolder
  #test
  #test2
  #test3
  #test4