trigger: none
pool: Hosted

resources:
 pipelines:
     - pipeline: MyPipeline
       source: ajayProject
       trigger: 
         branches:
          exclude:
              - master
steps:
 - script: echo "hello world"
 - download: MyPipeline

