resources:
 builds:
     - build: MyJenkins
       connection: rmcdpjenkins3
       type: Jenkins
       source: ReleaseManagement/RMCDP/RMCDPProject-FreeStyle

jobs:
- template: artifacts/templates/dowloadJenkinsTemplate.yml
  parameters:
    name: Ubuntu1604
    pool: $[ coalesce(variables.ubuntu1604, 'Hosted Ubuntu 1604') ]
